#@data/values
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
#@overlay/match missing_ok=True
helm_chart: 
  repository_dispatch:
    types: [helm_release]
  chart_names: chart helm base
