# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: github-sample
templates:
  engine: ytt
  defaults:
    libs:
      - workflow-configuration/helm-chart
    dependencies:
      - https://raw.githubusercontent.com/CoverGo/ci-workflow-libraries/v2.5/.gflows