#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on":
  repository_dispatch:
    types:
    - helm_release
  workflow_dispatch:
    inputs:
      version:
        description: 'Helm chart version'
        required: true
        default: 'x.x.x'
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      CHART_NAMES: #@ common.get_value(getattr(getattr(data.values,"helm_chart"),"chart_names"),"test")
      TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.event.client_payload.ref_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      working-directory: ${{ env.CHART_NAMES }}
      run: |-
        helm lint .
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
        helm dependency update
        export TRIMTAG=${TAG//v}
        yq -i '.covergo-app.image.tag = strenv(TRIMTAG)' values.yaml
        helm package . --version $TRIMTAG --app-version $TRIMTAG
        helm push $(ls *-$TRIMTAG.tgz | head -n1) oci://ghcr.io/covergo/charts
