#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on": #@ common.workflow_triggers_dispatch(getattr(getattr(data.values,"helm_chart"),"repository_dispatch"))
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      CHART_NAMES: #@ common.get_value(getattr(getattr(data.values,"helm_chart"),"chart_names"),"test")
      GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.HELM_CHART_SA_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      working-directory: ./$CHART_NAMES
      run: |-
        helm lint .
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
        helm package . --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
        helm push .*-${{ github.ref_name }}.tgz oci://ghcr.io/covergo/charts