#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on": #@ common.workflow_triggers_with_path(getattr(getattr(data.values,"helm_chart"),"git"))
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      CHART_NAMES: #@ common.get_value(getattr(getattr(data.values,"helm_chart"),"chart_names"),"test")
      GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.HELM_CHART_SA_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      run: |-
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
        for f in $CHART_NAMES; do
          helm lint $f
          helm dependency update $f
          helm package $f
          helm push $(ls *$f*.tgz | head -n1) oci://ghcr.io/covergo/charts
        done