#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on": #@ common.workflow_triggers_with_path(getattr(getattr(data.values,"helm_chart"),"git"))
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      GKE_ZONE: us-central1
      GC_PROJECT_ID: k8s-saas
      CHART_PATH: base/backend/$CHART_NAME
      CHART_NAME: covergo-achievements
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      run: |-
        ${{ secrets.HELM_CHART_SA_KEY }} | helm registry login https://${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.GC_PROJECT_ID }} -u _json_key --password-stdin
        helm version
        helm package ${{ env.CHART_PATH }}
        helm push $(ls *.tgz | head -n1) oci://${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.GC_PROJECT_ID }}/${{ env.CHART_NAME }}