#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on": #@ common.workflow_triggers_with_path(getattr(getattr(data.values,"helm_chart"),"git"))
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      CHART_NAMES: #@ common.get_value(getattr(getattr(data.values,"helm_chart"),"chart_names"),"test")
      GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.HELM_CHART_SA_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      run: |-
        for f in $CHART_NAMES; do
          echo "${GCLOUD_SERVICE_ACCOUNT_KEY}" | helm registry login https://us-central1-docker.pkg.dev/gcp-helm-registry/covergo-helm-production -u _json_key --password-stdin
          helm version
          helm package $f
          helm push $(ls *$f*.tgz | head -n1) oci://us-central1-docker.pkg.dev/gcp-helm-registry/covergo-helm-production
        done