#@ load("@ytt:data", "data")
#@ load("common.lib.yml", "common")

name: Release Helm Chart
"on": #@ common.workflow_triggers_dispatch(getattr(getattr(data.values,"helm_chart"),"repository_dispatch"))
jobs:
  release_helmchart:
    name: release-helmchart
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.10
    env:
      CHART_NAMES: #@ common.get_value(getattr(getattr(data.values,"helm_chart"),"chart_names"),"test")
      TAG: ${{ github.event.client_payload.ref_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Package & Upload Helm Chart
      working-directory: ${{ env.CHART_NAMES }}
      run: |-
        helm lint .
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
        helm dependency update
        echo $TAG
        yq -i '.covergo-app.image.tag = "$TAG"' values.yaml
        helm package . --version $TAG --app-version $TAG
        helm push $(ls *-$TAG.tgz | head -n1) oci://ghcr.io/covergo/charts
    - name: Push changes
      run: |
        git config user.name "release-bot"
        git config user.email "release-bot@covergo.com"
        git commit -s -m"[release-bot] Updating helm chart image version" values.yaml
        git push
